
model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss

    ddconfig:
      attn_type: none
      double_z: false
      z_channels: 3
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 32
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 11
        disc_weight: 0.75
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    wrap: false
    num_workers: 8
    train:
      target: ldm.data.her2.HER2Dataset
      params:
        folder: /cluster/ub46ukev/latent-diffusion/data/patched_her2/train
        target: label
        cluster: True
        aug: True
    validation:
      target: ldm.data.her2.HER2Dataset
      params:
        folder: /cluster/ub46ukev/latent-diffusion/data/patched_her2/val
        target: label
        cluster: True
        aug: True

lightning:
  trainer:
    log_every_n_steps: 50
    progress_bar_refresh_rate: 50
    gpus: 2
    accelerator: ddp
    accumulate_grad_batches: 4