model:
  base_learning_rate: 5.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    ckpt_path: D:/HER2/projects/latent-diffusion/trained_models/cells.ckpt
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: train/loss
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 64
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        embed_dim: 16
        n_classes: 7
        key: class_label
data:
  target: predict.DataModuleFromConfig
  params:
    batch_size: 16
    wrap: false
    num_workers: 4
    train:
      target: ldm.data.cells.DatasetCells
      params:
        folder: D:/HER2/data/cells
        cluster: False
        aug: False

lightning:
  trainer:
    log_every_n_steps: 50
    progress_bar_refresh_rate: 50
    gpus: 1
    accelerator: gpu